### ISSUE TITLE
 User authorization failed: sig param is incorrect when init

### ISSUE THREAD

**Issue by noname007** [vladkens/VK#17]
when run 
```php
$vk = new VK\VK('{APP_ID}', '{API_SECRET}', '{ACCESS_TOKEN}');
```
it throws the exception
```
   User authorization failed: sig param is incorrect
```

**Comment by noname007** [comment]
who can help me ?

**Comment by PatSpiegel** [comment]
script good work, its only u problem

**Comment by noname007** [comment]
ref the https://vk.com/dev/api_requests colud't resolve the problem.
at last onle let the front application remove the nohttps and the problem was resolved temporarily...
