### ISSUE TITLE
Set $this->auth = true after setAccessToken

### ISSUE THREAD

**Issue by akmetainfo** [vladkens/VK#21]
Получил на тестовой машине "вечный" токен, в продакшене не используется получение getAccessToken, просто читается из конфигурационного файла.

При этом обратил внимание, что нужно убирать проверку if ($vk->isAuth()) потому что setAccessToken никак не устанавливает признак авторизации.

Мне кажется, тут логическая нестыковка: токен установили, а признак авторизации не выставили.

**Comment by vladkens** [comment]
Теперь isAuth сообщает о том что токен установлен но не обязательно валиден. Чтобы проверить валидность токена можно использовать checkAccessToken метод.

Спасибо.
